chore!(traefik): rename lego-related variable to be traefik-prefixed
famedly/ansible-collection-network pull request #62
Opened 2024-06-23 09:24 UTC by jdreichmann

2024-06-23 09:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/famedly/ansible-collection-network?pullRequest=62) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/famedly/ansible-collection-network?pullRequest=62) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/famedly/ansible-collection-network?pullRequest=62) it.</sub>

2024-06-23 10:26 UTC, jcgruenhage requested changes

2024-06-23 10:26 UTC, jcgruenhage commented on roles/traefik/defaults/main.yml
> +# Excepts a path where traefik can template its renewal script into
Accepts or expects fit here semantically, excepts doesn't make sense.

2024-07-09 16:18 UTC, jdreichmann commented
poke @jcgruenhage

2025-08-13 21:52 UTC, closed without merging